name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        addrsize: ["64"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install required packages
        if: runner.os == 'Linux'
        run: sudo apt install -y  gettext gperf
      - uses: secondlife/action-autobuild@v3
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
        with:
          public: true
